global:
  scrape_interval: 15s # How often Prometheus pulls data
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-employee-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Prometheus uses Docker's internal DNS to resolve these container names
      - targets: ['employee-app-blue:8080', 'employee-app-green:8080']
