spring.application.name=employee-management-portal

# DevOps: Expose the health check endpoint for Jenkins
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
