spring.application.name=employee-management-portal

# DevOps: Expose the health check endpoint for Jenkins
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Expose health, info, and prometheus endpoints over HTTP
management.endpoints.web.exposure.include=health,info,prometheus

# Provide detailed health information
management.endpoint.health.show-details=always
